# Setup
title:        Intellireview 2.0
tagline:      Update Intellireview to the new 2018 standard
baseurl:      "/~djtranslator"
locale:       "en"

# About/contact
author:
  name:       Django Translators
  url:        ""

# Gems
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
