# Setup
title:        CIAS Class Cal
tagline:      A Software Engineering Senior Project
baseurl:      ""
locale:       "en"

# About/contact
author:
  name:       The Team
  url:        http://yourhomepage.com 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
