# Setup
title:        Tops Product Locator
tagline:      A mobile/desktop application to locate products in Tops Friendly Market stores
baseurl:      ""
locale:       "en"

# About/contact
author:
  name:       The Team
  url:        topsproductlocator.se.rit.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
